version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - pip install -r requirements.txt

  pre_build:
    commands:
      # Discover and run unit tests. For more information, see <https://docs.djangoproject.com/en/2.0/topics/testing/overview/>
      - python manage.py test

      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml

  post_build:
    commands:
      # Update the project ID in the template-configuration.json file so AWS CloudFormation can tag project resources.
      # This replaces the tagging placeholder with the project ARN.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json
artifacts:
  type: zip
  files:
    - template-export.yml
    - template-configuration.json
